<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Analysis-1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Summary_files/libs/clipboard/clipboard.min.js"></script>
<script src="Summary_files/libs/quarto-html/quarto.js"></script>
<script src="Summary_files/libs/quarto-html/popper.min.js"></script>
<script src="Summary_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Summary_files/libs/quarto-html/anchor.min.js"></script>
<link href="Summary_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Summary_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Summary_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Summary_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Summary_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Analysis-1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>The data described below deals with three different types of flour that were inoculated with E. coli. The goal was to study the survival persistence of E. coli. Each type of flour was given three different levels of water and the colony-forming-unit (CFU) per gram was measured at ten unequally spaced time points.</p>
</section>
<section id="about-the-data" class="level3">
<h3 class="anchored" data-anchor-id="about-the-data">About the data</h3>
<p>The data set provided by the client includes 270 observations. The three types of flour are wheat, buck, and cake, with each accounting for 90 of the observations. These are recorded in the categorical variable <em>Flour</em>. The variable <em>aw</em> measures the water activity with the three water levels 0.45, 0.55 and 0.65 units. <em>Day</em> and <em>REP</em> record the day and repetition respectively. The data set also includes the log of CFU/g instead of the untransformed values. This variable is titled <em>Ecoli_Load</em> in the data set.</p>
<section id="distribution-of-e.coli-measurements" class="level4">
<h4 class="anchored" data-anchor-id="distribution-of-e.coli-measurements">Distribution of E.coli Measurements</h4>
<p>The first information to consider is the apparent distribution of our dependent variable, which in this case will be the log of CFU/g. To use a linear model or linear mixed model, the independent variable should be approximately normally distributed. We can check this assumption with two plots.</p>
<p>The first plot is a histogram. If the data follows an approximate normal distribution, the histogram should follow a bell shape. The histogram below, shows signs of a mild left skew, but this does not mean the data is not approximately normal.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Summary_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Summary_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The second plot to consider is the qq plot above. A QQ plot uses theoretical values from a normal distribution as the x-axis, and the observations from the data on the y-axis. If the data is normally distributed, most of the points should fall on a 45 degree line in the positive direction. In our plot we can see that the majority of the points do fall close to this line. There is some values further from the line at both tails, but this is not uncommon.</p>
<p>Looking at both the histogram and the qq plot, the assumption that the log of the E.coli measurements are approximately normally distributed is not clearly violated. Therefore, a linear model or mixed model will be used later, as opposed to the generalized version of either.</p>
</section>
<section id="impact-of-flour-type" class="level4">
<h4 class="anchored" data-anchor-id="impact-of-flour-type">Impact of Flour Type</h4>
<p>One key question in this study is what effect the flour type has on the E.coli levels. There are some differences in the log of CFU/g we can get from the data set right away as it relates to flour. Buck flour has a mean log CFU/g of roughly 5.49, a median of 5.59, and a standard deviation of 0.85. Cake flour has a mean of 5.53, a median of 5.91, and a standard deviation of 1.73. The same three metrics for wheat flour are roughly 4.61, 4.67, and 1.27 respectively. These differences will become more apparent in some of the graphs below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Summary_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To get an idea of this graphically, let’s consider the box plot above. We can see the interquartile range (IQR) of the three types of wheat vary, with cake flour being the most spread out followed by wheat flour. These differences match the standard deviations discussed above. What stands out about in the box plot are a handful of outliers at the lower end of the box plot for the cake flour observations. This suggests that some samples had much lower E. coli loads compared to the bulk of the data. Neither of the other two types show any outliers.</p>
<p>From both the plot above and the metrics discussed earlier we can say cake flour tends to have the highest E. coli load, followed by buck flour, then wheat flour. This indicates that the type of flour may play a role in the persistence of E. coli.</p>
<p>To see whether the suspected relationship between the flour type and the persistence of E. coli is significant, we can view an ANOVA table. The ANOVA table below is based on a simple linear model, which follows the form $$</p>
<p>log((CFU/g)_{i})=_0 + _1 <em>i +</em> </p>
<p>$$ where <span class="math inline">\(\beta_0\)</span> represents the y-intercept, <span class="math inline">\(\beta_1\)</span> represents the coefficient to the type of flour, for the three flower types which are denoted by <span class="math inline">\(i\)</span>. _{i} represents the error. The results of this model can be seen below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Flour         2   49.0  24.493   13.73 2.11e-06 ***
Residuals   267  476.3   1.784                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We can see the relationship between the type of flour and the log of CFU/g of E.coli is highly significant. Now we will look at contrasts based on the type of flour. Since we are comparing the effect three different flour types have on the E.coli measurement, we should use Tukey’s Honest Significant Difference (HSD) test. This method is less likely to result in a false positive, also called a type I error, when comparing multiple treatments.</p>
<p>(https://www.blackwellpublishing.com/specialarticles/jcn_8_304.pdf)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Ecoli_Load ~ Flour, data = Data_1)

$Flour
                  diff        lwr        upr     p adj
Cake-Buck   0.04666667 -0.4226149  0.5159482 0.9701759
Wheat-Buck -0.87933333 -1.3486149 -0.4100518 0.0000433
Wheat-Cake -0.92600000 -1.3952815 -0.4567185 0.0000155</code></pre>
</div>
</div>
<p>Tukey’s HSD test indicates significant differences in our E. coli measurement between wheat and both buck and cake flour types. There is no significant difference between cake and buck flour types.</p>
</section>
<section id="other-variables" class="level4">
<h4 class="anchored" data-anchor-id="other-variables">Other variables</h4>
<p>While we have created a simple model, including more information may be an improvement. As discussed previously, the data comes with three other variable. Among the other variables, knowing effect the water activity and time have on the E.coli levels is important.</p>
</section>
<section id="water-activity" class="level4">
<h4 class="anchored" data-anchor-id="water-activity">Water Activity</h4>
<p>First let’s consider the effect water activity has on both the E.coli levels and the types of flour. This can be done through an interaction plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Summary_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The interaction plot above shows that higher water levels seem to increase the E.coli measurement among the buck flour observations while decreasing the measurement among the cake flour observations. The wheat flour observations have little change according to the graph. To answer the question of whether this is significant or not, a new model could be fit with water activity added, but first let’s consider another variable.</p>
</section>
<section id="day-of-measurement" class="level4">
<h4 class="anchored" data-anchor-id="day-of-measurement">Day of Measurement</h4>
<p>Knowing how E.coli levels change over time also seems like important information to consider. Below is a plot of our E.coli measurements over time, which comes from the variable <em>Day</em>. There is a trend with the E.coli levels going down as the day of the measurement increases.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Summary_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="anova-tables" class="level3">
<h3 class="anchored" data-anchor-id="anova-tables">ANOVA Tables</h3>
<p>Using the variables that were just graphically investigated, let’s create a linear model to see the statistical effect <em>Flour</em>, <em>Day</em>, and <em>aw</em> have on the E.coli measurement, which is still in log form.</p>
<p>In the ANOVA below <em>Flour</em>, <em>Day</em>, and <em>aw</em> are considered independent variables, while the E.coli measurement is the dependent variable, as before.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
Flour         2   49.0    24.5  53.613 &lt;2e-16 ***
Day           1  355.0   355.0 777.155 &lt;2e-16 ***
aw            1    0.2     0.2   0.514  0.474    
Residuals   265  121.1     0.5                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Above we can see the type of flour is still highly significant, as is the variable <em>Day</em>, which makes sense from what we saw in the time plot. The water activity is not significant though, as the p-value is above 0.5. Despite not being significant, the water activity may be important within the context of the study, so it will remain in the model for now.</p>
<p>One thing missing in the ANOVA above is any interaction terms. Below is an ANOVA designed to account for possible interactions between the variables. Both <em>Flour</em> and <em>Day</em> are still highly significant, and we can see their interaction is as well. While the water activity on its own is not significant, the interaction between it and the type of flour is at a marginal level. Therefore we should keep both <em>aw</em> and its interaction with <em>Flour</em> in the model, but may consider removing others.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq  F value  Pr(&gt;F)    
Flour          2   49.0    24.5   83.748 &lt; 2e-16 ***
Day            1  355.0   355.0 1213.982 &lt; 2e-16 ***
aw             1    0.2     0.2    0.803 0.37116    
Flour:Day      2   40.9    20.5   69.925 &lt; 2e-16 ***
Flour:aw       2    3.1     1.5    5.244 0.00586 ** 
Day:aw         1    0.5     0.5    1.733 0.18923    
Flour:Day:aw   2    1.1     0.6    1.941 0.14569    
Residuals    258   75.5     0.3                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The ANOVA results of removing the interaction between water activity and the day along with the interaction of all three are shown below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq  F value  Pr(&gt;F)    
Flour         2   49.0    24.5   82.917 &lt; 2e-16 ***
Day           1  355.0   355.0 1201.943 &lt; 2e-16 ***
aw            1    0.2     0.2    0.795 0.37353    
Flour:Day     2   40.9    20.5   69.232 &lt; 2e-16 ***
Flour:aw      2    3.1     1.5    5.192 0.00615 ** 
Residuals   261   77.1     0.3                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="accounting-for-replications" class="level3">
<h3 class="anchored" data-anchor-id="accounting-for-replications">Accounting for Replications</h3>
<p>With three models to consider now, the last variable in the data set, <em>REP</em>, should be considered. <em>REP</em> measures the replications. This variable should be included as a random effect. Doing so allows us account for additional variability. It also means we are now working with a linear mixed model instead of the mixed model above. The resulting ANOVA table from adding the random effect to our third model is below.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'Matrix' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lmerTest' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
          Sum Sq Mean Sq NumDF DenDF   F value    Pr(&gt;F)    
Flour       9.58    4.79     2   259   16.8854 1.279e-07 ***
Day       355.05  355.05     1   259 1251.2774 &lt; 2.2e-16 ***
aw          0.23    0.23     1   259    0.8272  0.363922    
Flour:Day  40.90   20.45     2   259   72.0735 &lt; 2.2e-16 ***
Flour:aw    3.07    1.53     2   259    5.4049  0.005016 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>In this model, which excludes two of the possible interaction terms but has a random , there is a similar level of significance as above.</p>
<p>In the ANOVA below, which includes terms for all possible interactions as well as, there are fewer values that appear significant. The day is considered highly significant when looking at the corresponding p-value, while the type of flour is now only moderately signifcant.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
             Sum Sq Mean Sq NumDF DenDF F value   Pr(&gt;F)    
Flour        2.0690  1.0345     2   256  3.6859 0.026414 *  
Day          4.2551  4.2551     1   256 15.1611 0.000126 ***
aw           0.0311  0.0311     1   256  0.1108 0.739455    
Flour:Day    0.4015  0.2007     2   256  0.7153 0.490037    
Flour:aw     0.3997  0.1999     2   256  0.7122 0.491553    
Day:aw       0.5068  0.5068     1   256  1.8057 0.180220    
Flour:Day:aw 1.1352  0.5676     2   256  2.0224 0.134452    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>When comparing the two mixed models that were used in the ANOVA tables, it would seem excluding two of the interaction terms increases the significance of the other variables in the model. Looking at an ANOVA is not all that must be done to queck the model though.</p>
</section>
<section id="checking-assumptions-of-the-potential-model" class="level3">
<h3 class="anchored" data-anchor-id="checking-assumptions-of-the-potential-model">Checking Assumptions of the Potential Model</h3>
<p>Before declaring a model, we should check whether a potential model corresponding to an ANOVA table above violates any assumptions around mixed models.</p>
<p>Let’s consider the mixed model that excluded two of the interaction terms first. The four plots below check some of the assumptions that must hold for this model to be used.</p>
<p>The QQ plot and histogram are similar to what was used above, excpet this time residuals are being plotted instead of E.coli levels. One of our assumptions is that the residuals are normally distributed, and by looking at the two plots, this assumption seems to hold.</p>
<p>Another assumption we need to check is whether the residuals have constant variance, also known as homoscedasticity. This can be done through the residuals vs.&nbsp;fitted values plot below. The plot shows little to no trend with the residuals, which is ideal. While there are more data points on the right side of the graph they still appear random, leading to the conclusion that the constant variance assumption holds.</p>
<p>The plot in the bottom right corner measures how the values generated by the model compare to the actual values observed in the data set. Most points falling on a 45 degree line is a good sign, as it seems the model’s predictions hold up based on our sample.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Summary_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Since all of the assumptions discussed above hold, the mixed model including only some interactions can be used.</p>
</section>
<section id="linear-mixed-model" class="level3">
<h3 class="anchored" data-anchor-id="linear-mixed-model">Linear Mixed Model</h3>
<p>After checking the assumptions we can confirm our model is</p>
<p><span class="math display">\[
\begin{align*}
\log\left(\frac{CFU}{g}\right)_{ijk} &amp;= \beta_0 + \beta_1 \cdot \text{Flour}_i + \beta_2 \cdot \text{Day}_j \\
&amp;\quad + \beta_3 \cdot \text{aw}_k + \beta_4 \cdot (\text{Flour}_i \times \text{Day}_j) \\
&amp;\quad + \beta_5 \cdot (\text{aw}_k \times \text{Flour}_i) + u_j + \epsilon_{ijk}
\end{align*}
\]</span></p>
<p>where <span class="math inline">\(\beta_b\)</span> for <span class="math inline">\(b=1,2,3,4,5\)</span> represent the fixed effect coefficients, <span class="math inline">\(u_{j}\)</span> represents the random effect associated with <em>REP</em>, and <span class="math inline">\(\epsilon_{ijk}\)</span> is the error term.</p>
<p>Now it is time to look at the full summary of our model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: Ecoli_Load ~ Flour * Day + aw * Flour + (1 | REP)
   Data: Data_1

REML criterion at convergence: 462.5

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.45985 -0.67130 -0.04201  0.49552  2.89721 

Random effects:
 Groups   Name        Variance Std.Dev.
 REP      (Intercept) 0.01689  0.1300  
 Residual             0.28375  0.5327  
Number of obs: 270, groups:  REP, 3

Fixed effects:
                 Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)      5.718458   0.393995 224.126721  14.514  &lt; 2e-16 ***
FlourCake        2.717035   0.546997 259.000000   4.967 1.23e-06 ***
FlourWheat      -0.070328   0.546997 259.000000  -0.129  0.89780    
Day             -0.019919   0.001588 259.000000 -12.547  &lt; 2e-16 ***
aw               0.913333   0.687685 259.000000   1.328  0.18531    
FlourCake:Day   -0.026779   0.002245 259.000000 -11.928  &lt; 2e-16 ***
FlourWheat:Day  -0.010729   0.002245 259.000000  -4.779 2.96e-06 ***
FlourCake:aw    -3.068333   0.972534 259.000000  -3.155  0.00179 ** 
FlourWheat:aw   -0.755000   0.972534 259.000000  -0.776  0.43827    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) FlorCk FlrWht Day    aw     FlrC:D FlrW:D FlrCk:
FlourCake   -0.694                                                 
FlourWheat  -0.694  0.500                                          
Day         -0.148  0.107  0.107                                   
aw          -0.960  0.691  0.691  0.000                            
FlourCak:Dy  0.105 -0.151 -0.075 -0.707  0.000                     
FlourWht:Dy  0.105 -0.075 -0.151 -0.707  0.000  0.500              
FlourCake:w  0.679 -0.978 -0.489  0.000 -0.707  0.000  0.000       
FlourWhet:w  0.679 -0.489 -0.978  0.000 -0.707  0.000  0.000  0.500</code></pre>
</div>
</div>
<p>Using the estimates above we can rewrite the model as <span class="math display">\[
\begin{align*}
\log\left(\frac{CFU}{g}\right)_{ijk} &amp;= 5.718458 + 2.717035 \cdot \text{Flour}_{cake} - 0.070328 \cdot \text{Flour}_{wheat} \\
&amp;\quad - 0.019919 \cdot \text{Day} + 0.913333 \cdot \text{aw} \\
&amp;\quad - 0.026779 \cdot (\text{Flour}_{cake} \times \text{Day}) - 0.010729 \cdot (\text{Flour}_{wheat} \times \text{Day}) \\
&amp;\quad - 3.068333 \cdot (\text{Flour}_{cake} \times \text{aw}) - 0.755000 \cdot (\text{Flour}_{wheat} \times \text{aw}) \\
&amp;\quad + u_j + \epsilon_{ijk}
\end{align*}
\]</span></p>
<p>Note buck flour is not shown. The reason for this is since the type of flour is a category variable, whenever the type of is buck, all terms involving cake or wheat flour will equal zero, and the remaining terms indicated buck flour.</p>
</section>
<section id="need-more-comparison-stuff-here-where-ryan-stopped" class="level1">
<h1>Need more comparison stuff here – WHERE RYAN STOPPED</h1>
<section id="model-comparison" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison">Model Comparison</h3>
<p>LM model AIC: 500.80 (lower is better) GLMM model AIC: 576.4 The LM model has a lower AIC, indicating a better fit based on this criterion.</p>
<p>BIC:</p>
<p>LM model BIC: 547.58 (lower is better) GLMM model BIC: 626.8 The LM model also has a lower BIC, further suggesting it is the better model by this criterion.</p>
<p><strong><em>Conclusion:</em></strong> AIC and BIC both indicate that the LM model fits the data better than the GLMM. However, model choice should also consider the assumptions about the data distribution:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 500.7978 547.5772</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>